/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get presigned S3 URLs for document uploads
         * @description Returns presigned PUT URLs for uploading documents directly to S3. Call this before submitting — upload files to S3 first, then POST /submissions with the S3 keys.
         */
        post: operations["presign_uploads_api_v1_uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit applicant documents for screening
         * @description Receives applicant data and document S3 keys as JSON. Documents must already be uploaded to S3 via presigned URLs from /uploads/presign. Creates the applicant record and enqueues extraction jobs.
         */
        post: operations["create_submission_api_v1_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{applicant_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get screening status for a submission
         * @description Returns the current screening status for an applicant. Status is PROCESSING while documents are being extracted and screened, or COMPLETED with a full screening report once assessment finishes.
         */
        get: operations["get_screening_status_api_v1_submissions__applicant_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake-form-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List intake form requests for an agency
         * @description Returns paginated intake form requests filtered by agency ID.
         */
        get: operations["list_intake_form_requests_api_v1_intake_form_requests_get"];
        put?: never;
        /**
         * Create an intake form request
         * @description Creates a new intake form request linking an applicant to a property. Agencies use this to invite prospective tenants or buyers to submit their documents.
         */
        post: operations["create_intake_form_request_api_v1_intake_form_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake-form-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an intake form request by ID */
        get: operations["get_intake_form_request_api_v1_intake_form_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applicants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List applicants by owner
         * @description Returns all applicants belonging to the specified owner (agency user), including submission status and screening reports.
         */
        get: operations["list_applicants_api_v1_applicants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applicants/{applicant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get applicant details with screening report
         * @description Returns full applicant details including their screening report if available.
         */
        get: operations["get_applicant_api_v1_applicants__applicant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicantDetailResponse */
        ApplicantDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone?: string | null;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Form Request Id
             * Format: uuid
             */
            form_request_id: string;
            /** Listing Type */
            listing_type: string;
            /** Property Type */
            property_type?: string | null;
            /** Property Value */
            property_value: number | null;
            /** Monthly Rent */
            monthly_rent: number | null;
            /** Property Title */
            property_title: string;
            /** Property Address */
            property_address: string;
            /** Status */
            status?: string | null;
            screening_report?: components["schemas"]["ScreeningReportResponse"] | null;
        };
        /** CreateIntakeFormRequestBody */
        CreateIntakeFormRequestBody: {
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Applicant Name */
            applicant_name: string;
            /** Applicant Email */
            applicant_email: string;
            /** Property Id */
            property_id: string;
            listing_type: components["schemas"]["ListingType"];
            property_type?: components["schemas"]["PropertyType"] | null;
            /** Applicant Phone */
            applicant_phone?: string | null;
            /** Property Title */
            property_title?: string | null;
            /** Property Price */
            property_price?: number | null;
            /** Property Address */
            property_address?: string | null;
        };
        /** CreateSubmissionRequest */
        CreateSubmissionRequest: {
            /** Nif */
            nif: string;
            /** Name */
            name: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Email */
            email: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Form Request Id
             * Format: uuid
             */
            form_request_id: string;
            listing_type: components["schemas"]["ListingType"];
            property_type: components["schemas"]["PropertyType"];
            /** Terms Accepted */
            terms_accepted: boolean;
            /** Documents */
            documents: components["schemas"]["UploadedDocumentSpec"][];
            /** Phone */
            phone?: string | null;
            /** Property Value */
            property_value?: number | null;
            /** Monthly Rent */
            monthly_rent?: number | null;
            /**
             * Property Title
             * @default n/a
             */
            property_title: string;
            /**
             * Property Address
             * @default n/a
             */
            property_address: string;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "ID_DOCUMENT" | "PROOF_OF_INCOME";
        /** FileUploadSpec */
        FileUploadSpec: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            document_type: components["schemas"]["DocumentType"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeFormRequestResponse */
        IntakeFormRequestResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Applicant Name */
            applicant_name: string;
            /** Applicant Email */
            applicant_email: string;
            /** Applicant Phone */
            applicant_phone: string | null;
            /** Property Id */
            property_id: string;
            /** Listing Type */
            listing_type: string;
            /** Property Type */
            property_type?: string | null;
            /** Property Title */
            property_title: string | null;
            /** Property Price */
            property_price: number | null;
            /** Property Address */
            property_address: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            submission?: components["schemas"]["SubmissionSummaryResponse"] | null;
        };
        /**
         * ListingType
         * @enum {string}
         */
        ListingType: "ARRENDAMENTO" | "VENDA";
        /** PresignedFileUpload */
        PresignedFileUpload: {
            /** Filename */
            filename: string;
            /** S3 Key */
            s3_key: string;
            /** Upload Url */
            upload_url: string;
            document_type: components["schemas"]["DocumentType"];
        };
        /** PresignedUploadRequest */
        PresignedUploadRequest: {
            /**
             * Form Request Id
             * Format: uuid
             */
            form_request_id: string;
            /** Files */
            files: components["schemas"]["FileUploadSpec"][];
        };
        /** PresignedUploadResponse */
        PresignedUploadResponse: {
            /** Upload Id */
            upload_id: string;
            /** Files */
            files: components["schemas"]["PresignedFileUpload"][];
        };
        /**
         * PropertyType
         * @enum {string}
         */
        PropertyType: "APARTAMENTO" | "MORADIA" | "TERRENO";
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH";
        /** ScreeningReportResponse */
        ScreeningReportResponse: {
            /**
             * Applicant Id
             * Format: uuid
             */
            applicant_id: string;
            risk_level: components["schemas"]["RiskLevel"];
            /** Identity Verified */
            identity_verified: boolean;
            /** Income Verified */
            income_verified: boolean;
            /** Dti Ratio */
            dti_ratio: number;
            /** Justification */
            justification: string;
            listing_type: components["schemas"]["ListingType"];
            property_type?: components["schemas"]["PropertyType"] | null;
            /** Average Monthly Income */
            average_monthly_income: number;
        };
        /** ScreeningStatusResponse */
        ScreeningStatusResponse: {
            /**
             * Applicant Id
             * Format: uuid
             */
            applicant_id: string;
            /** Status */
            status: string;
            report?: components["schemas"]["ScreeningReportResponse"] | null;
        };
        /** SubmissionResponse */
        SubmissionResponse: {
            /**
             * Applicant Id
             * Format: uuid
             */
            applicant_id: string;
            /** Documents Uploaded */
            documents_uploaded: number;
            /** Message */
            message: string;
        };
        /** SubmissionSummaryResponse */
        SubmissionSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UploadedDocumentSpec */
        UploadedDocumentSpec: {
            /** S3 Key */
            s3_key: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            document_type: components["schemas"]["DocumentType"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    presign_uploads_api_v1_uploads_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_api_v1_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_status_api_v1_submissions__applicant_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_intake_form_requests_api_v1_intake_form_requests_get: {
        parameters: {
            query: {
                organization_id: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeFormRequestResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intake_form_request_api_v1_intake_form_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntakeFormRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeFormRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intake_form_request_api_v1_intake_form_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeFormRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applicants_api_v1_applicants_get: {
        parameters: {
            query: {
                organization_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicantDetailResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_applicant_api_v1_applicants__applicant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicantDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
