/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a source document
         * @description Accepts a PDF or DOCX file, stores it in S3, computes a content hash for deduplication, and creates a `ContractSourceDocument` record with status `uploaded`.
         */
        post: operations["upload_source_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a source document
         * @description Returns the full metadata for a single source document, including current upload status.
         */
        get: operations["get_document_source_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List source documents
         * @description Returns a summary list of all source documents with contract name, page count, and section count.
         */
        get: operations["list_documents_source_documents__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-documents/{document_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get source document detail with parse data
         * @description Returns full document metadata including the raw Reducto parse output JSON.
         */
        get: operations["get_document_detail_source_documents__document_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-documents/{document_id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request parsing of a source document
         * @description Enqueues an async parse job (OCR + layout analysis) for the given document. The document is split into ordered `SourceSection` rows once parsing completes.
         */
        post: operations["parse_source_documents__document_id__parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-documents/{document_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request extraction from a source document
         * @description Enqueues an async extraction job that uses an LLM to pull structured field evidence from each parsed section. Results are stored as `SourceFieldEvidence` rows.
         */
        post: operations["extract_source_documents__document_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/source-documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get review bundle for a source document
         * @description Returns the document's parsed sections together with all extracted field evidence so that a reviewer can inspect, accept, or correct them in one view.
         */
        get: operations["get_review_bundle_review_source_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/source-sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update source section review
         * @description Sets the review status of a parsed section (e.g. `accepted`, `corrected`, `rejected`) and optionally provides a corrected `normalized_text`.
         */
        patch: operations["update_section_review_review_source_sections__section_id__patch"];
        trace?: never;
    };
    "/review/source-field-evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update field evidence review
         * @description Sets the review status of an extracted field (e.g. `accepted`, `corrected`) and optionally provides a `corrected_value_json`.
         */
        patch: operations["update_field_evidence_review_review_source_field_evidence__evidence_id__patch"];
        trace?: never;
    };
    "/template-versions/from-source/{source_document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create template version from source document
         * @description Promotes a fully reviewed source document into a new template version. Copies sections as `TemplateSection` rows with Jinja render slots, creates field bindings, conditions, and party slots derived from the extraction results.
         */
        post: operations["create_from_source_template_versions_from_source__source_document_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/template-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a template version
         * @description Returns the full template version record including its schema, rules, and status.
         */
        get: operations["get_version_template_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a template version
         * @description Partially updates a draft template version. Allowed fields: `review_notes`, `status`, `schema_json`, `computed_rules_json`.
         */
        patch: operations["update_version_template_versions__version_id__patch"];
        trace?: never;
    };
    "/template-versions/template-sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a template section
         * @description Partially updates an individual template section — title, render template, condition expression, optionality, repeatability, or status.
         */
        patch: operations["update_section_template_versions_template_sections__section_id__patch"];
        trace?: never;
    };
    "/template-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a template version
         * @description Transitions a template version from `draft` / `review` to `approved` and sets it as the current version on the parent `ContractTemplate`. Fails if the version is already published.
         */
        post: operations["publish_version_template_versions__version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generated-contracts/from-crm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create generated contract from CRM data
         * @description Resolves CRM contact and property records, maps them onto the template version's field bindings and party slots, and creates a `GeneratedContract` in `draft` status.
         */
        post: operations["create_from_crm_generated_contracts_from_crm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generated-contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a generated contract
         * @description Returns the full generated contract including its rendered schema and current status.
         */
        get: operations["get_contract_generated_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generated-contracts/{contract_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a generated contract
         * @description Renders each section of the generated contract through the Jinja template engine, produces a PDF artifact, stores it in S3, and returns the artifact metadata.
         */
        post: operations["render_contract_generated_contracts__contract_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_source_documents_upload_post */
        Body_upload_source_documents_upload_post: {
            /** File */
            file: string;
            /**
             * Organization Id
             * Format: uuid
             * @description ID of the owning organization.
             */
            organization_id: string;
        };
        /**
         * CreateGeneratedContractFromCRMRequest
         * @description Payload to generate a new contract from CRM records.
         */
        CreateGeneratedContractFromCRMRequest: {
            /**
             * Template Version Id
             * Format: uuid
             * @description Template version to use for generation.
             */
            template_version_id: string;
            /**
             * Crm Contact Id
             * @description CRM identifier of the contact (buyer/tenant).
             */
            crm_contact_id: string;
            /**
             * Crm Property Id
             * @description CRM identifier of the property.
             */
            crm_property_id: string;
            /**
             * Organization Id
             * @description Optional owning client ID.
             */
            organization_id?: string | null;
        };
        /**
         * CreateTemplateVersionFromSourceResponse
         * @description Summary returned after promoting a source document into a template version.
         */
        CreateTemplateVersionFromSourceResponse: {
            /**
             * Id
             * Format: uuid
             * @description ID of the newly created template version.
             */
            id: string;
            /**
             * Contract Template Id
             * Format: uuid
             * @description Parent contract template ID.
             */
            contract_template_id: string;
            /**
             * Version Number
             * @description Sequential version number within the template.
             */
            version_number: number;
            /**
             * Status
             * @description Initial status (always `draft`).
             */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FieldEvidenceRead
         * @description A single extracted field value with its provenance.
         */
        FieldEvidenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Section Id
             * @description Section this evidence was extracted from.
             */
            source_section_id?: string | null;
            /**
             * Field Key
             * @description Canonical field key (e.g. `rent_amount`, `start_date`).
             */
            field_key: string;
            /**
             * Field Value Json
             * @description Extracted value (JSON-typed).
             */
            field_value_json?: unknown;
            /**
             * Source Text
             * @description Original text span the value was extracted from.
             */
            source_text?: string | null;
            /**
             * Page Number
             * @description Page where the evidence was found.
             */
            page_number?: number | null;
            /**
             * Confidence
             * @description Extraction confidence (0–1).
             */
            confidence?: string | null;
            /**
             * Review Status
             * @description Review status: `pending`, `accepted`, `corrected`, or `rejected`.
             */
            review_status: string;
            /**
             * Corrected Value Json
             * @description Reviewer-corrected value, if any.
             */
            corrected_value_json?: unknown;
        };
        /**
         * GeneratedContractRead
         * @description Full metadata of a generated contract.
         */
        GeneratedContractRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Template Id
             * Format: uuid
             * @description Parent contract template ID.
             */
            contract_template_id: string;
            /**
             * Template Version Id
             * Format: uuid
             * @description Template version used for generation.
             */
            template_version_id: string;
            /** Organization Id */
            organization_id?: string | null;
            /** Crm Contact Id */
            crm_contact_id?: string | null;
            /** Crm Property Id */
            crm_property_id?: string | null;
            /**
             * Status
             * @description Lifecycle status: `draft`, `generated`, `reviewed`, `signed`, or `archived`.
             */
            status: string;
            /**
             * Input Payload Json
             * @description Resolved input payload used for rendering.
             */
            input_payload_json: {
                [key: string]: unknown;
            };
            /**
             * Rendered Schema Json
             * @description Rendered schema snapshot at generation time.
             */
            rendered_schema_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RenderGeneratedContractResponse
         * @description Artifact metadata returned after rendering a contract to PDF.
         */
        RenderGeneratedContractResponse: {
            /**
             * Id
             * Format: uuid
             * @description Artifact ID.
             */
            id: string;
            /**
             * Artifact Type
             * @description Artifact format (e.g. `pdf`).
             */
            artifact_type: string;
            /**
             * Storage Url
             * @description S3 URL of the rendered artifact.
             */
            storage_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceDocumentDetail
         * @description Detail view of a source document with raw parse data.
         */
        SourceDocumentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Contract Name */
            contract_name?: string | null;
            /** File Url */
            file_url: string;
            /** Page Count */
            page_count?: number | null;
            /** Upload Status */
            upload_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parse Response Json */
            parse_response_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SourceDocumentListItem
         * @description Summary info for a source document in a listing.
         */
        SourceDocumentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Contract Name */
            contract_name?: string | null;
            /** File Url */
            file_url: string;
            /** Page Count */
            page_count?: number | null;
            /** Sections Count */
            sections_count: number;
            /** Upload Status */
            upload_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceDocumentRead
         * @description Full metadata of a source document.
         */
        SourceDocumentRead: {
            /**
             * Id
             * Format: uuid
             * @description Unique identifier of the source document.
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             * @description ID of the organization that owns this document.
             */
            organization_id: string;
            /**
             * Filename
             * @description Original filename.
             */
            filename: string;
            /**
             * Storage Url
             * @description S3 object URL.
             */
            storage_url: string;
            /**
             * Mime Type
             * @description MIME type.
             */
            mime_type: string;
            /**
             * Page Count
             * @description Number of pages detected after parsing.
             */
            page_count?: number | null;
            /**
             * Language Code
             * @description ISO 639-1 language code detected after parsing.
             */
            language_code?: string | null;
            /**
             * Document Hash
             * @description SHA-256 content hash used for deduplication.
             */
            document_hash: string;
            /**
             * Upload Status
             * @description Current status: `uploaded`, `parsed`, `extracted`, or `failed`.
             */
            upload_status: string;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when the document was uploaded.
             */
            created_at: string;
        };
        /**
         * SourceReviewBundleRead
         * @description Aggregated review data for a source document — sections plus field evidence.
         */
        SourceReviewBundleRead: {
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Filename */
            filename: string;
            /** Upload Status */
            upload_status: string;
            /**
             * Sections
             * @description Parsed sections in display order.
             */
            sections: components["schemas"]["SourceSectionRead"][];
            /**
             * Field Evidence
             * @description All extracted field evidence across sections.
             */
            field_evidence: components["schemas"]["FieldEvidenceRead"][];
        };
        /**
         * SourceSectionRead
         * @description A parsed section of a source document.
         */
        SourceSectionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Section Key
             * @description Machine-readable section identifier.
             */
            section_key?: string | null;
            /**
             * Title
             * @description Human-readable section title.
             */
            title?: string | null;
            /**
             * Page Start
             * @description First page of the section (1-based).
             */
            page_start?: number | null;
            /**
             * Page End
             * @description Last page of the section (1-based).
             */
            page_end?: number | null;
            /**
             * Sort Order
             * @description Display order within the document.
             */
            sort_order: number;
            /**
             * Extracted Text
             * @description Raw text extracted by the parser.
             */
            extracted_text?: string | null;
            /**
             * Normalized Text
             * @description Reviewer-corrected or normalized text.
             */
            normalized_text?: string | null;
            /**
             * Classification Confidence
             * @description Model confidence for section classification (0-1).
             */
            classification_confidence?: string | null;
            /**
             * Review Status
             * @description Review status: `pending`, `accepted`, `corrected`, `rejected`, `merged`, or `split`.
             */
            review_status: string;
        };
        /**
         * TemplateVersionRead
         * @description Full metadata of a template version.
         */
        TemplateVersionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Template Id
             * Format: uuid
             * @description Parent contract template ID.
             */
            contract_template_id: string;
            /**
             * Source Document Id
             * @description Source document this version derives from.
             */
            source_document_id?: string | null;
            /**
             * Version Number
             * @description Sequential version number.
             */
            version_number: number;
            /**
             * Render Engine
             * @description Template engine used for rendering (e.g. `jinja`).
             */
            render_engine: string;
            /**
             * Schema Json
             * @description JSON schema describing the template's input fields.
             */
            schema_json: {
                [key: string]: unknown;
            };
            /**
             * Computed Rules Json
             * @description Pre-computed conditional rules for section inclusion.
             */
            computed_rules_json: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @description Lifecycle status: `draft`, `review`, `approved`, `deprecated`, or `archived`.
             */
            status: string;
            /** Review Notes */
            review_notes?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Approved At */
            approved_at?: string | null;
        };
        /**
         * UpdateFieldEvidenceReviewRequest
         * @description Payload to update the review status of an extracted field.
         */
        UpdateFieldEvidenceReviewRequest: {
            /**
             * Review Status
             * @description New review status (e.g. `accepted`, `corrected`).
             */
            review_status: string;
            /**
             * Corrected Value Json
             * @description Corrected value to replace the extracted value.
             */
            corrected_value_json?: unknown;
        };
        /**
         * UpdateSourceSectionReviewRequest
         * @description Payload to update the review status of a parsed section.
         */
        UpdateSourceSectionReviewRequest: {
            /**
             * Review Status
             * @description New review status (e.g. `accepted`, `corrected`, `rejected`).
             */
            review_status: string;
            /**
             * Normalized Text
             * @description Corrected text to replace the extracted text.
             */
            normalized_text?: string | null;
        };
        /**
         * UpdateTemplateSectionRequest
         * @description Partial update payload for a single template section.
         */
        UpdateTemplateSectionRequest: {
            /**
             * Title
             * @description Section display title.
             */
            title?: string | null;
            /**
             * Render Template
             * @description Jinja template string for this section.
             */
            render_template?: string | null;
            /**
             * Condition Expression
             * @description Boolean expression that gates section inclusion.
             */
            condition_expression?: string | null;
            /**
             * Is Optional
             * @description Whether the section can be omitted.
             */
            is_optional?: boolean | null;
            /**
             * Is Repeatable
             * @description Whether the section can repeat for multiple parties.
             */
            is_repeatable?: boolean | null;
            /**
             * Status
             * @description Section status: `draft`, `approved`, or `hidden`.
             */
            status?: string | null;
        };
        /**
         * UpdateTemplateVersionRequest
         * @description Partial update payload for a template version.
         */
        UpdateTemplateVersionRequest: {
            /**
             * Review Notes
             * @description Free-text review notes.
             */
            review_notes?: string | null;
            /**
             * Status
             * @description New lifecycle status.
             */
            status?: string | null;
            /**
             * Schema Json
             * @description Replacement input-field schema.
             */
            schema_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Computed Rules Json
             * @description Replacement computed rules.
             */
            computed_rules_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * UploadSourceDocumentResponse
         * @description Metadata returned after a successful source document upload.
         */
        UploadSourceDocumentResponse: {
            /**
             * Id
             * Format: uuid
             * @description Unique identifier of the source document.
             */
            id: string;
            /**
             * Filename
             * @description Original filename as provided during upload.
             */
            filename: string;
            /**
             * Storage Url
             * @description S3 object URL where the file is stored.
             */
            storage_url: string;
            /**
             * Mime Type
             * @description MIME type of the uploaded file (e.g. `application/pdf`).
             */
            mime_type: string;
            /**
             * Upload Status
             * @description Current status: `uploaded`, `parsed`, `extracted`, or `failed`.
             */
            upload_status: string;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when the document was uploaded.
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    upload_source_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_documents_upload_post"];
            };
        };
        responses: {
            /** @description The newly created source document metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSourceDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_source_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source document metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_source_documents__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of source document summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentListItem"][];
                };
            };
        };
    };
    get_document_detail_source_documents__document_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source document detail with parse response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_source_documents__document_id__parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledgement with the parse run ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_source_documents__document_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledgement with the extraction run ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_bundle_review_source_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review bundle containing sections and field evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceReviewBundleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_section_review_review_source_sections__section_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceSectionReviewRequest"];
            };
        };
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_field_evidence_review_review_source_field_evidence__evidence_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFieldEvidenceReviewRequest"];
            };
        };
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_from_source_template_versions_from_source__source_document_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The newly created template version summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTemplateVersionFromSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_template_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template version metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_version_template_versions__version_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateVersionRequest"];
            };
        };
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_section_template_versions_template_sections__section_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateSectionRequest"];
            };
        };
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_version_template_versions__version_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_from_crm_generated_contracts_from_crm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGeneratedContractFromCRMRequest"];
            };
        };
        responses: {
            /** @description The newly created generated contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedContractRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_generated_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated contract metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedContractRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_contract_generated_contracts__contract_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rendered artifact (type, storage URL, checksum). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderGeneratedContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
